### PR TITLE
[BUGFIX] Removed ratepay from demoshop

### PR DESCRIPTION
**Pull request by alex-galych**
Removed ratepay bundle from demoshop.

### CODE REVIEW

**Comment by dereuromark** [comment]
@stereomon Do you think this is OK to merge?
Just in project the ratepay bundle will still exist (for us right now), and in demoshop it is completely removed.

**Comment by dereuromark** [comment]
@alex-galych I rebased it.

**Comment by dereuromark** [comment]
What about braintree and other eco thingss in composer json?

**Comment by alex-galych** [comment]
@dereuromark We will have separate tickets for them.

**Pull request merged**
